included:
  - ${PROJECT_NAME}
  - ${PROJECT_NAME}/../ToDoListTests
  - ${PROJECT_NAME}/..ToDoListUITests
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  - 420
  - 500
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
